# Generated by Django 4.0.4 on 2022-04-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('key', 'note')},
        ),
    ]
